// Copyright 2017-2022 @polkadot/json-serve authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/json-serve', path: 'auto', type: 'auto', version: '0.49.5-1' };
