// Copyright 2017-2021 @polkadot/json-serve authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@polkadot/json-serve', version: '0.39.2-1' };
