// Copyright 2017-2022 @polkadot/signer-cli authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/signer-cli', path: 'auto', type: 'auto', version: '0.50.6' };
