// Copyright 2017-2022 @polkadot/vanitygen authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@polkadot/vanitygen', version: '0.48.10-0' };
