// Copyright 2017-2023 @polkadot/vanitygen authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/vanitygen', path: 'auto', type: 'auto', version: '0.53.3-0-x' };
