// Copyright 2017-2024 @polkadot/monitor-rpc authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/monitor-rpc', path: 'auto', type: 'auto', version: '0.56.3-0-x' };
