// Copyright 2017-2023 @polkadot/monitor-rpc authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/monitor-rpc', path: 'auto', type: 'auto', version: '0.52.30-0-x' };
