// Copyright 2017-2024 @polkadot/api-cli authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/api-cli', path: 'auto', type: 'auto', version: '0.56.7-2-x' };
