// Copyright 2017-2021 @polkadot/api-cli authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@polkadot/api-cli', version: '0.48.2' };
