// Copyright 2017-2021 @polkadot/metadata-cmp authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@polkadot/metadata-cmp', version: '0.30.2-1' };
