name: PR
on: [pull_request]

jobs:
  pr:
    strategy:
      matrix:
        step: ['lint', 'test', 'build']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_SCRIPTS: false
    steps:
    - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e
    - name: ${{ matrix.step }}
      run: |
        yarn install --immutable | grep -v 'YN0013'
        yarn ${{ matrix.step }}
