name: PR
on: [pull_request]

jobs:
  pr:
    continue-on-error: true
    strategy:
      matrix:
        step: ['lint', 'test', 'build']
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_SCRIPTS: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
    - name: ${{ matrix.step }}
      run: |
        yarn install --immutable | grep -v 'YN0013'
        yarn ${{ matrix.step }}
