name: Master
on:
  push:
    branches:
      - master

jobs:
  build_code:
    name: Build Code
    if: "! contains(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.GH_PAT }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        GH_PAT: ${{ secrets.GH_PAT }}
        GH_TOKEN: ${{ secrets.GH_PAT }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        yarn install --frozen-lockfile
        yarn polkadot-ci-ghact-build

  build_docker:
    name: Build Docker
    if: "contains(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
      env:
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        ./docker.sh build
        ./docker.sh publish
