name: Master
on:
  push:
    branches:
      - master

jobs:
  master:
    strategy:
      matrix:
        step: ['build:release']
    name: ${{ matrix.step }}
    if: "! contains(github.event.head_commit.message, '[CI Skip]') && github.repository == 'polkadot-js/tools'"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.GH_PAT }}
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: ${{ matrix.step }}
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        GH_PAT: ${{ secrets.GH_PAT }}
        GH_TOKEN: ${{ secrets.GH_PAT }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        yarn install --immutable | grep -v 'YN0013'
        yarn ${{ matrix.step }}

  docker:
    name: docker
    if: "contains(github.event.head_commit.message, '[CI Skip]') && github.repository == 'polkadot-js/tools'"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: docker
      env:
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        ./docker.sh build
        ./docker.sh publish
